language: node_js
sudo: false
node_js:
  - "6"
install:
  - cd server && npm install
script:
  - cd server && npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8