language: node_js
sudo: false
os: osx
node_js:
  - "8"
install:
  - cd server && npm install && cd .. && cd client && npm install && cd ..
script:
  - cd server && npm test && cd .. && cd client && npm test && cd ..
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8